package com.kalah.model;

import java.util.UUID;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.Getter;

@Getter
@DynamoDBTable(tableName = "game")
@AllArgsConstructor
@Data
public class Game {

	@DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute
	private Board board;

	@DynamoDBAttribute
	private Player winner;

	@DynamoDBAttribute
	private Player turn;

	public Game() {
		this.id = UUID.randomUUID().toString();
		this.board = new Board();
	}
}
